### ISSUE TITLE
dynamichttp profile docker not started

### ISSUE THREAD

**Issue by timukas** [MythicC2Profiles/dynamichttp#3]
Hi,

Installed latest and greatest (as of today) Mythic on Linux x64 with dynamichttp profile.

Dynamichttp profile is not listed in UI "C2 Profile" list.

'`docker logs dynamichttp`' shows '**ParameterType.File**' error

```
  File "/usr/local/lib/python3.11/enum.py", line 783, in __getattr__
    raise AttributeError(name) from None
AttributeError: File
Traceback (most recent call last):
  File "/Mythic/main.py", line 2, in <module>
    from mythic.dynamicHTTP import *
  File "/Mythic/mythic/dynamicHTTP.py", line 14, in <module>
    class DynamicHTTP(C2Profile):
  File "/Mythic/mythic/dynamicHTTP.py", line 34, in DynamicHTTP
    parameter_type=ParameterType.File,
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 783, in __getattr__
    raise AttributeError(name) from None
AttributeError: File
```

Looks like something is broken.

Any fixes/ideas?

**Comment by its-a-feature** [comment]
Good catch! The built-in PyPi library for that docker container wasn't updated. I just kicked off the build (https://github.com/MythicMeta/Mythic_Docker_Templates/actions/runs/6921154646), so you should be good to try rebuilding ( `sudo ./mythic-cli build dynamichttp`)

**Comment by its-a-feature** [comment]
did rebuilding the container work for you?

**Comment by timukas** [comment]
`./mythic-cli build dynamichttp` did not help (still had errors).

But clean install worked well. Now dynamichttp is present in GUI and no errors in container.
